### ISSUE TITLE
Proposal for Reimplementation in Rust

### ISSUE THREAD

**Issue by ghost** [DaniD3v/digiDownload#2]
Dear @DaniD3v,

I hope this message finds you well. I am writing to propose a potential enhancement to your repository, digiDownload.

Having reviewed the current implementation, I believe that reimplementing the program in Rust could offer several benefits. Rust is renowned for its performance and memory safety, particularly its safe handling of concurrency. This could potentially improve the efficiency and reliability of the program.

I understand that such a transition would be a significant undertaking, and I am not suggesting it lightly. I believe the long-term benefits would justify the effort. Of course, this is just a suggestion, and I respect that the final decision is yours.

If you are open to this idea, I would be more than happy to discuss it further and potentially contribute to the reimplementation process.

Thank you for considering my proposal. I look forward to your feedback.

Best regards,
matteodev8

**Comment by DaniD3v** [comment]
> Best regards, matteodev8

more like ChatGPT

I'm actually working on that rn tho.
Did you know about that or did we just get really lucky?

**Comment by ghost** [comment]
i need bwm 1 book but nono work and thought it might be the time to write this **issue that is totally written by myself** for a updated rust implementation

**Comment by DaniD3v** [comment]
Yeah I know, the digi4school hosted books have been broken for a while now. I'll fix it until friday
